name: Build Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4

      - name: Build Debug Version
        run: dotnet build -c Debug -o bin/Debug
      
      - name: Build Release Version
        run: dotnet build -c Release -o bin/Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-test
          path: bin
