name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag (e.g., v1.2.3)"
        required: true
        default: "v0.0.0"

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false

      - name: Taggify Version
        id: taggify
        run: |
          if ($env:GITHUB_EVENT_NAME -eq 'push') {
            $tag = $env:GITHUB_REF -replace 'refs/tags/', ''
            echo "Tag from push event: $tag"
            echo "tag=$tag" >> $env:GITHUB_ENV
          } else {
            echo "Tag from workflow_dispatch input: ${{ github.event.inputs.tag }}"
            echo "tag=${{ github.event.inputs.tag }}" >> $env:GITHUB_ENV
          }

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4

      - name: Build
        run: dotnet build -c Release -o bin/Release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/Release/SherkeyXD.MiSideSoundsLoader.dll
          body: "Download `SherkeyXD.MiSideSoundsLoader.dll` and place it under `BepInEx/plugins`."
          tag_name: ${{ env.tag }}
